### ISSUE TITLE
Change settings link to use cpTrigger instead of hardcoded /admin/settings URI?

### ISSUE THREAD

**Issue by mildlygeeky** [wbrowar/adminbar#1]
Love this, as I do a lot of Drupal work and find that content authors love having an admin bar at the top of the screen for editing the current content.

That being said, I cannot use this as it currently stands as I often override the cpTrigger, so /admin/settings does not work for me.

If instead you grabbed the cpTrigger (below) in your variables, it would make the settings link more versatile when users have overridden their default trigger:

`craft()->config->get('cpTrigger') . '/settings'`

**Comment by wbrowar** [comment]
Thanks for the tip, @mildlygeeky. I wasn't aware of cpTrigger, but I can see why you'd want to swap it out.

I've changed the URL in the main template to `<a href="/{{ craft.config.cpTrigger }}/settings">Settings</a>`. I think the leading slash should be okay, but I'll see if it causes any issues. Can you think of a use case where it would be a problem?

I've also done a bunch of Drupal development, too, so I'm glad you can find this useful. If you can think of any ways to improve it or any features that could be useful I'd appreciate your thoughts.
