### ISSUE TITLE
Remove admin bar from Live Preview

### ISSUE THREAD

**Issue by AbbeyDesign** [wbrowar/adminbar#13]
Though, technically, I could wrap the admin bar in a `{% if not craft.request.isLivePreview %}` it would be better if the admin bar did not show up in live preview by default.

**Comment by wbrowar** [comment]
Hey David, that totally makes sense. There's not a great reason why it's there in Live Preview. I'll add a check to remove it in the next release.

**Comment by wbrowar** [comment]
David, this is all set in the latest release!
