### ISSUE TITLE
Edit Label in the adminbar

### ISSUE THREAD

**Issue by AbbeyDesign** [wbrowar/adminbar#14]
Would prefer the "Edit" button in the adminbar to just say "Edit" without appending the section name. Our section names don't always make sense and it makes this button a little ugly/confusing/inconsistent.

**Some examples**
Edit Pages
Edit For Rent
Edit Inventory

**Comment by wbrowar** [comment]
Sure. That's a pretty easy change. I'll create a setting that can turn that off.

Thanks again for the feedback, and please keep it coming!

**Comment by wbrowar** [comment]
David, this is fixed in this release, too. There's a new setting for `adminbar.php`, called `displayDefaultEditSection`. If you set this to `false`, it will omit the section name from the "Edit" link.
