### ISSUE TITLE
Error when adding admin bar via CP or template

### ISSUE THREAD

**Issue by stuart-mccoy** [wbrowar/adminbar#2]
When I try to add the adminbar to the site using either method I get an error stating **"Impossible to invoke a method ("can") on a NULL variable ("")"**.

**Comment by hamishtaplin** [comment]
This happens if you're not logged in. Pretty serious!

**Comment by stuart-mccoy** [comment]
Appears to be the case. I thought I was signed when I originally tested this but apparently not. My CP session must have timed out at some point and caused AdminBar to fail as well. Still a serious bug though.

**Comment by wbrowar** [comment]
Thanks, guys! It shouldn't give you that error any more as of 1.2.1.
