### ISSUE TITLE
PHP Errors on PHP5.3

### ISSUE THREAD

**Issue by danethomas** [wbrowar/adminbar#3]
I've run into couple of issues enabling this on a server running php 5.3.x

It worked without a hitch locally, but on the production server I'm getting:

`Fatal error: Using $this when not in object context in ../craft/plugins/adminbar/AdminbarPlugin.php on line 18`

I also had to change https://github.com/wbrowar/craft-admin-bar/blob/master/adminbar/services/AdminbarService.php#L23-L30 to use `array()` rather than just `[]`

Any help would be appreciated and looking forward to your multi entry solution ;-)

**Comment by wbrowar** [comment]
Thanks for the heads up, Dane! I've fixed both of these and I set up a 5.3 local environment, so I'll try to test against that for future releases.

As far as multi-entry goes, I'm still thinking about how this works and in what situations it's helpful. If you have any suggestions, please let me know.
