### ISSUE TITLE
Reorganize repo so it can be used as a submodule

### ISSUE THREAD

**Issue by ghost** [wbrowar/adminbar#5]
If the repo is restructured so that the `/services` ,`/templates`, `/variables` and `AdminBarPlugin.php` are at the top level of the repo, then others could use it as a Git Submodule in their Craft projects under the `/plugins` dir (this make updates, pr's etc, easier) 

LICENSE and README, etc can stay at the top, as Craft will just ignore those.

**Comment by wbrowar** [comment]
@lwilkowskeBC I'm going to keep it as-is for now. Is there any way I can make it easier without restructuring everything? Like symlinks or something?

**Comment by wbrowar** [comment]
Hey, @lwilkowskeBC, since Craft 3 is a ways away, I've re-organized the repo so it'll work better with Git. Thanks for being patient.

**Comment by ghost** [comment]
Thanks!
