### ISSUE TITLE
Category pages throw exception

### ISSUE THREAD

**Issue by danielparas** [wbrowar/adminbar#9]
Hi, I updated to the latest version of your plugin and when accessing a page with "category" not "entry" I get the following exception thrown:

`Craft\CategoryModel and its behaviors do not have a method or closure named "section".`

In ideas please?

Thanks in advance.
Daniel

**Comment by wbrowar** [comment]
@danielparas thanks for the heads up. It was definitely a bug that I missed in testing. I did a quick fix, so please download the latest version and see if that works.

**Comment by danielparas** [comment]
Thanks for the quick reply @wbrowar !

Unfortunatly I'm still getting the same exception :( - Is there any other info I can give you to help?

**Comment by danielparas** [comment]
Issue possibly happening here:

``` /home/vagrant/cms/craft/plugins/adminbar/AdminbarPlugin.php(68): Craft\AdminbarService->bar(Craft\CategoryModel, "#d85b4b", "primary")```

Particularly at line 67:

``` $element = craft()->urlManager->getMatchedElement(); ```

**Comment by danielparas** [comment]
The exception seems to be mentioning line 11 from bar.html

```
{% set entrySectionName = entry.elementType == 'Entry' ? ' ' ~ entry.section.name : '' %}
```

As seen in the exception:

```
// line 11
$context["entrySectionName"] = (($this->getAttribute((isset($context["entry"]) ? $context["entry"] : null), "section", array(), "any", true, true)) ? ((" " . $this->getAttribute($this->getAttribute((isset($context["entry"]) ? $context["entry"] : $this->getContext($context, "entry")), "section", array()), "name", array()))) : (""));
```

**Comment by wbrowar** [comment]
Hmm.. I'll look into it some more.

**Comment by wbrowar** [comment]
@danielparas are you using the embed tag and passing in the category object, or are you using the Auto Embed version?

**Comment by danielparas** [comment]
@wbrowar sorry for the delay. I'm using the auto embed version. Thanks!

**Comment by wbrowar** [comment]
Hey @danielparas, I'll continue to look into it, but I just took out what should be the offending code, so you won't get that error. Please try the updated version and let me know if that fixes it for now.

**Comment by wbrowar** [comment]
Hey @danielparas, I'm closing this since 2.0 fixes this.
